### ISSUE TITLE
API key versionnée

### ISSUE THREAD

**Issue by gileri** [DoFabien/proxy-ortho-ign#1]
N'est-ce pas risqué de diffuser la clé d'API fournie par l'IGN ?
https://github.com/DoFabien/proxy-ortho-ign/blob/master/index.js#L11

Si c'est le cas il vaudrait mieux la stocker dans un fichier séparé non-commité

**Comment by DoFabien** [comment]
Bonjour,
La clé est lié à une IP et est publique, elle apparaît dans l'url des
tuiles, donc je ne pense pas que ça soit un problème

--
Fabien

2016-11-24 19:08 GMT+01:00 Eric G. <notifications@github.com>:

**Comment by gileri** [comment]
Si elle n'est pas utilisable par une autre IP publique en effet je pense pas qu'il y ait de problème.
